<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-19T21:44:38 IST" name="Default suite" finished-at="2023-09-19T21:44:40 IST" duration-ms="1180">
    <groups>
    </groups>
    <test started-at="2023-09-19T21:44:38 IST" name="Default test" finished-at="2023-09-19T21:44:40 IST" duration-ms="1180">
      <class name="Session_12.DeserializationJSonDemo">
        <test-method signature="createUser()[pri:0, instance:Session_12.DeserializationJSonDemo@543588e6]" started-at="2023-09-19T21:44:38 IST" name="createUser" finished-at="2023-09-19T21:44:40 IST" duration-ms="1164" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Prachi expected:<Prachi> but was:<check for name.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Prachi expected:<Prachi> but was:<check for name.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at Session_12.DeserializationJSonDemo.createUser(DeserializationJSonDemo.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
      </class> <!-- Session_12.DeserializationJSonDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
